name: deploy-rss-6k

on:
  push:
    branches: [main]
    paths:
      - "functions/rss-6k/**"
      - ".github/workflows/deploy-rss-6k.yml"
  workflow_dispatch:

concurrency:
  group: deploy-rss-6k
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: rss-6k
          region: europe-west1
          source: functions/rss-6k
          flags: --port=8080 --memory=1Gi --cpu=1 --concurrency=80 --service-account=846229407230-compute@developer.gserviceaccount.com --clear-base-image
          env_vars: |
            FUNCTION_TARGET=monitorear_sec_event
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            GCP_LOCATION=${{ secrets.GCP_LOCATION }}
            CORREO_ORIGEN=${{ secrets.CORREO_ORIGEN }}
            CORREO_DESTINO=${{ secrets.CORREO_DESTINO }}
            PASSWORD_APP=${{ secrets.PASSWORD_APP }}

